### PR TITLE
Fix README

### PR DESCRIPTION
**Pull request by democat3457**

### CODE REVIEW

**Comment by StollD** [comment]
```
To be clear, I don't want to smear anyone or flex about it...
Feel free to ignore me entirely or tell me and I will shut up about it.
```

But I just looked at the PR that is open on Kopernicus/wiki, and then
at this, and I got like a small heart attack.

Why does a simple README change (which is also not really a fix), need
to be 3 commits? One commit should do one thing, and nothing more.
Splitting up a task into multiple commits makes the whole history 
unreadable, even if it is a rather large change.

And tbh especially those "Merged x into y" commits are really annoying
because they provide nothing valuable.

I know I am a bit picky about it, since I try to keep my histories 
rather clean (I do make mistakes too though). But I think that a clean 
history can only help a project in the long term.

If you want some tips on how I try to avoid those things, feel free to
ping me about it (Discord or here). Otherwise, as said above, feel free
to ignore me or tell me to shut up.

**Comment by democat3457** [comment]
How do you avoid unnecessary commits?

**Comment by StollD** [comment]
Well, first of all: Using a good client is key. GitHub Desktop somewhat
works, but if you really want to take a deep dive into git, use 
GitKraken, or even the commandline (it is actually not that hard!)

Second: Always keep your branches up to date. I don't know if GitHub
Desktop has this feature, but in GitKraken you can add the upstream
(i.e. this repo) as a "remote" and reset your master to the state that
is used here. Deleting and recreating the fork works too but it is 
rather crude. But keeping them up to date avoids those "Merged xy"
commits.

Then, third: Do the entire thing first, and then commit it. Don't do it 
in chunks. Commit it into a new branch (not into master). If you notice 
that you forgot something, either delete the branch and remake the 
commit (simply copy over the files, so you don't loose your changes),
or "amend" the commit (GitKraken can do this I think, I doubt GH 
Desktop has that feature tbh.). Ameding adds your changes to the 
already created commit, instead of making a new one.

I am not sure how useful all of this is to be honest. I hope it helps
you, but if it doesn't don't worry.

**Comment by democat3457** [comment]
:+1: Time to *git* GitKraken then!

**Comment by DeltaDizzy** [comment]
With regards to commit amending, is `git stash apply` roughly the same thing, or did I misread the git docs?

**Comment by democat3457** [comment]
Isn't `git stash apply` taking changes out of the stash and putting them back on the uncommitted list?

**Comment by DeltaDizzy** [comment]
Maybe. In the meantime, should this PR remain open or is another try going to be made?

**Comment by democat3457** [comment]
I guess this can remain open/be merged because even though it's an eyesore, it's still valid changes.

**Comment by DeltaDizzy** [comment]
Actually there is an option to squash them into 1 commit...

**Comment by democat3457** [comment]
Oh.

**Pull request merged**
