### PR TITLE
Atmosphere and AFG

### PR DESCRIPTION
**Pull request by democat3457**
IDK what happened with the commits... (sorry Thomas :disappointed:) Still learning GitKraken. :octopus:

### CODE REVIEW

**Comment by DeltaDizzy** [comment]
So, `the Atmosphere { } subnode`. Imo, it is redundant int he same way as `the VertexHeightMap { }  PQSMod`.

**Comment by democat3457** [comment]
Hasn't the `XYZ { } (sub)node` syntax been going on for all of the base pages?

**Comment by DeltaDizzy** [comment]
Yes, but we should be consistent.

**Comment by democat3457** [comment]
True... @StollD

**Comment by StollD** [comment]
I would say `the XY {} node` is ok. My complaint about VHM was, that you wrote
`the VHM {} PQSMod` - the PQSMod isn't called `VertexHeightMap  { }`, it is
called `VertexHeightMap`. The *node* however is called `VertexHeightMap { }`,
so either write `the XY PQSMod` or `the XY { } node`.

Also, I tried to fix the history, in case you want to pull from that I can open
a PR: https://github.com/StollD/wiki/commits/bugfix/history

Always use `reset to upstream/master` or so, don't merge it into your branch.
That causes those merge commits. Reset just forces the history to be the same.

And always fetch your remotes before resetting, so you have the latest version
locally.

**Comment by DeltaDizzy** [comment]
> Always use reset to upstream/master

Does this mean always merge feature branches into an exact copy of `origin/master`?

**Pull request merged**
